// Meridian's plugin protocol: the wire form of the design plan's §11.4 Emitter
// interface.
//
// The protocol carries a compiled resource tree to a target plugin and carries
// back the artifact that tree compiles to. It deliberately does not model
// running anything: Runner is a separate concern kept outside the compile
// chain, so `meridian plan` stays a pure function over this service alone.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: meridian/plugin/v1/plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EdgeKind keeps an ordering constraint and a deferred trigger structurally
// distinct, because they are not the same concept and targets compile them
// differently.
type EdgeKind int32

const (
	EdgeKind_EDGE_KIND_UNSPECIFIED EdgeKind = 0
	// dependsOn: `from` must be applied before `to`.
	EdgeKind_EDGE_KIND_HARD_ORDER EdgeKind = 1
	// notifies: `to` is triggered if `from` reports a change. It constrains
	// nothing about apply order.
	EdgeKind_EDGE_KIND_NOTIFY EdgeKind = 2
)

// Enum value maps for EdgeKind.
var (
	EdgeKind_name = map[int32]string{
		0: "EDGE_KIND_UNSPECIFIED",
		1: "EDGE_KIND_HARD_ORDER",
		2: "EDGE_KIND_NOTIFY",
	}
	EdgeKind_value = map[string]int32{
		"EDGE_KIND_UNSPECIFIED": 0,
		"EDGE_KIND_HARD_ORDER":  1,
		"EDGE_KIND_NOTIFY":      2,
	}
)

func (x EdgeKind) Enum() *EdgeKind {
	p := new(EdgeKind)
	*p = x
	return p
}

func (x EdgeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_meridian_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (EdgeKind) Type() protoreflect.EnumType {
	return &file_meridian_plugin_v1_plugin_proto_enumTypes[0]
}

func (x EdgeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeKind.Descriptor instead.
func (EdgeKind) EnumDescriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// Position is a point in a source document, carried so a failure raised inside
// a plugin can still be reported against the line the author wrote.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	DocIdx        int32                  `protobuf:"varint,2,opt,name=doc_idx,json=docIdx,proto3" json:"doc_idx,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Position) GetDocIdx() int32 {
	if x != nil {
		return x.DocIdx
	}
	return 0
}

func (x *Position) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Resource is one unconditional unit of desired state. Every compile-time
// `when` has already been evaluated before a tree reaches this protocol, so a
// plugin never has to reason about whether a resource will really be applied.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	State string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// params_json is the resource's parameters as a JSON object.
	//
	// It is JSON bytes rather than google.protobuf.Struct because Struct models
	// every number as a double: a port of 8080 would arrive as 8080.0 and change
	// the emitted artifact. Deterministic, byte-identical compilation is a
	// guiding principle, so the wire format preserves integers.
	ParamsJson []byte `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	// runtime_when is a condition evaluated on the node at apply time. Only a
	// target whose capabilities include runtime_condition may accept one.
	RuntimeWhen string `protobuf:"bytes,5,opt,name=runtime_when,json=runtimeWhen,proto3" json:"runtime_when,omitempty"`
	// index is the resource's declaration order in the source document, kept so a
	// target that reorders resources still has the original tiebreak.
	Index         int32     `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	Pos           *Position `protobuf:"bytes,7,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Resource) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *Resource) GetRuntimeWhen() string {
	if x != nil {
		return x.RuntimeWhen
	}
	return ""
}

func (x *Resource) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Resource) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

type Edge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To    string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Kind  EdgeKind               `protobuf:"varint,3,opt,name=kind,proto3,enum=meridian.plugin.v1.EdgeKind" json:"kind,omitempty"`
	// action is the notify action, for example "restart"; empty for an ordering
	// edge.
	Action        string    `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Pos           *Position `protobuf:"bytes,5,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Edge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Edge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Edge) GetKind() EdgeKind {
	if x != nil {
		return x.Kind
	}
	return EdgeKind_EDGE_KIND_UNSPECIFIED
}

func (x *Edge) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Edge) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

// ResourceGraph is a whole compiled document: its resources in deterministic
// apply order, the edges between them, and the host they configure.
type ResourceGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceGraph) Reset() {
	*x = ResourceGraph{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGraph) ProtoMessage() {}

func (x *ResourceGraph) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGraph.ProtoReflect.Descriptor instead.
func (*ResourceGraph) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceGraph) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceGraph) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ResourceGraph) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResourceGraph) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ResourceGraph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

// Capabilities is a target's honest declaration of what it can express. It is
// the mechanism behind the no-silent-capability-loss principle.
type Capabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NativeNotify     bool                   `protobuf:"varint,1,opt,name=native_notify,json=nativeNotify,proto3" json:"native_notify,omitempty"`
	SyntheticNotify  bool                   `protobuf:"varint,2,opt,name=synthetic_notify,json=syntheticNotify,proto3" json:"synthetic_notify,omitempty"`
	RuntimeCondition bool                   `protobuf:"varint,3,opt,name=runtime_condition,json=runtimeCondition,proto3" json:"runtime_condition,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Capabilities) GetNativeNotify() bool {
	if x != nil {
		return x.NativeNotify
	}
	return false
}

func (x *Capabilities) GetSyntheticNotify() bool {
	if x != nil {
		return x.SyntheticNotify
	}
	return false
}

func (x *Capabilities) GetRuntimeCondition() bool {
	if x != nil {
		return x.RuntimeCondition
	}
	return false
}

// Artifact is the complete output of a compile: relative path to file content.
// It is data rather than files on disk, which is what lets a plan be pure.
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         map[string]string      `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Artifact) GetFiles() map[string]string {
	if x != nil {
		return x.Files
	}
	return nil
}

// Warning is a compile-time notice that does not fail the build but changes
// what an operator should expect from the artifact.
type Warning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Warning) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Warning) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Warning) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// CompileError is a target refusing to compile something.
//
// It travels as a field of a successful response rather than as a gRPC status
// error on purpose: a target rejecting a resource type it cannot express is the
// capability contract working as designed, not a fault. Status errors stay
// reserved for genuine transport and plugin failures, so a host can tell the
// two apart.
type CompileError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Pos           *Position              `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileError) Reset() {
	*x = CompileError{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileError) ProtoMessage() {}

func (x *CompileError) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileError.ProtoReflect.Descriptor instead.
func (*CompileError) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *CompileError) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CompileError) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *CompileError) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CompileError) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version is the wire protocol the plugin speaks. A host refuses a
	// version it does not implement rather than guessing.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// sdk_version is the SDK the plugin was compiled against, reported rather
	// than inferred, per the release policy.
	SdkVersion string `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// resource_types lists every IR resource type this target maps, sorted.
	ResourceTypes []string      `protobuf:"bytes,4,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	Capabilities  *Capabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *DescribeResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *DescribeResponse) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *DescribeResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type EmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Graph *ResourceGraph         `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	// data_json is the resolved hierarchy data as a JSON object, carried for the
	// same reason params are: to preserve the value types the author wrote.
	DataJson      []byte `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *EmitRequest) GetGraph() *ResourceGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *EmitRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type EmitResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Artifact *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Warnings []*Warning             `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// error is set when the target could not compile the tree. When it is set,
	// artifact and warnings are meaningless.
	Error         *CompileError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_meridian_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *EmitResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *EmitResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *EmitResponse) GetError() *CompileError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_meridian_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_meridian_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1fmeridian/plugin/v1/plugin.proto\x12\x12meridian.plugin.v1\"c\n" +
	"\bPosition\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x17\n" +
	"\adoc_idx\x18\x02 \x01(\x05R\x06docIdx\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"\xce\x01\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\fR\n" +
	"paramsJson\x12!\n" +
	"\fruntime_when\x18\x05 \x01(\tR\vruntimeWhen\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x05R\x05index\x12.\n" +
	"\x03pos\x18\a \x01(\v2\x1c.meridian.plugin.v1.PositionR\x03pos\"\xa4\x01\n" +
	"\x04Edge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.meridian.plugin.v1.EdgeKindR\x04kind\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12.\n" +
	"\x03pos\x18\x05 \x01(\v2\x1c.meridian.plugin.v1.PositionR\x03pos\"\xbb\x01\n" +
	"\rResourceGraph\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12:\n" +
	"\tresources\x18\x04 \x03(\v2\x1c.meridian.plugin.v1.ResourceR\tresources\x12.\n" +
	"\x05edges\x18\x05 \x03(\v2\x18.meridian.plugin.v1.EdgeR\x05edges\"\x8b\x01\n" +
	"\fCapabilities\x12#\n" +
	"\rnative_notify\x18\x01 \x01(\bR\fnativeNotify\x12)\n" +
	"\x10synthetic_notify\x18\x02 \x01(\bR\x0fsyntheticNotify\x12+\n" +
	"\x11runtime_condition\x18\x03 \x01(\bR\x10runtimeCondition\"\x83\x01\n" +
	"\bArtifact\x12=\n" +
	"\x05files\x18\x01 \x03(\v2'.meridian.plugin.v1.Artifact.FilesEntryR\x05files\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\aWarning\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\x80\x01\n" +
	"\fCompileError\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12.\n" +
	"\x03pos\x18\x04 \x01(\v2\x1c.meridian.plugin.v1.PositionR\x03pos\"\x11\n" +
	"\x0fDescribeRequest\"\xdf\x01\n" +
	"\x10DescribeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0eresource_types\x18\x04 \x03(\tR\rresourceTypes\x12D\n" +
	"\fcapabilities\x18\x05 \x01(\v2 .meridian.plugin.v1.CapabilitiesR\fcapabilities\"c\n" +
	"\vEmitRequest\x127\n" +
	"\x05graph\x18\x01 \x01(\v2!.meridian.plugin.v1.ResourceGraphR\x05graph\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\"\xb9\x01\n" +
	"\fEmitResponse\x128\n" +
	"\bartifact\x18\x01 \x01(\v2\x1c.meridian.plugin.v1.ArtifactR\bartifact\x127\n" +
	"\bwarnings\x18\x02 \x03(\v2\x1b.meridian.plugin.v1.WarningR\bwarnings\x126\n" +
	"\x05error\x18\x03 \x01(\v2 .meridian.plugin.v1.CompileErrorR\x05error*U\n" +
	"\bEdgeKind\x12\x19\n" +
	"\x15EDGE_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EDGE_KIND_HARD_ORDER\x10\x01\x12\x14\n" +
	"\x10EDGE_KIND_NOTIFY\x10\x022\xab\x01\n" +
	"\aEmitter\x12U\n" +
	"\bDescribe\x12#.meridian.plugin.v1.DescribeRequest\x1a$.meridian.plugin.v1.DescribeResponse\x12I\n" +
	"\x04Emit\x12\x1f.meridian.plugin.v1.EmitRequest\x1a .meridian.plugin.v1.EmitResponseB:Z8github.com/ZanattaMichael/meridian-core/pkg/sdk/pluginpbb\x06proto3"

var (
	file_meridian_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_meridian_plugin_v1_plugin_proto_rawDescData []byte
)

func file_meridian_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_meridian_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_meridian_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meridian_plugin_v1_plugin_proto_rawDesc), len(file_meridian_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_meridian_plugin_v1_plugin_proto_rawDescData
}

var file_meridian_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meridian_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_meridian_plugin_v1_plugin_proto_goTypes = []any{
	(EdgeKind)(0),            // 0: meridian.plugin.v1.EdgeKind
	(*Position)(nil),         // 1: meridian.plugin.v1.Position
	(*Resource)(nil),         // 2: meridian.plugin.v1.Resource
	(*Edge)(nil),             // 3: meridian.plugin.v1.Edge
	(*ResourceGraph)(nil),    // 4: meridian.plugin.v1.ResourceGraph
	(*Capabilities)(nil),     // 5: meridian.plugin.v1.Capabilities
	(*Artifact)(nil),         // 6: meridian.plugin.v1.Artifact
	(*Warning)(nil),          // 7: meridian.plugin.v1.Warning
	(*CompileError)(nil),     // 8: meridian.plugin.v1.CompileError
	(*DescribeRequest)(nil),  // 9: meridian.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil), // 10: meridian.plugin.v1.DescribeResponse
	(*EmitRequest)(nil),      // 11: meridian.plugin.v1.EmitRequest
	(*EmitResponse)(nil),     // 12: meridian.plugin.v1.EmitResponse
	nil,                      // 13: meridian.plugin.v1.Artifact.FilesEntry
}
var file_meridian_plugin_v1_plugin_proto_depIdxs = []int32{
	1,  // 0: meridian.plugin.v1.Resource.pos:type_name -> meridian.plugin.v1.Position
	0,  // 1: meridian.plugin.v1.Edge.kind:type_name -> meridian.plugin.v1.EdgeKind
	1,  // 2: meridian.plugin.v1.Edge.pos:type_name -> meridian.plugin.v1.Position
	2,  // 3: meridian.plugin.v1.ResourceGraph.resources:type_name -> meridian.plugin.v1.Resource
	3,  // 4: meridian.plugin.v1.ResourceGraph.edges:type_name -> meridian.plugin.v1.Edge
	13, // 5: meridian.plugin.v1.Artifact.files:type_name -> meridian.plugin.v1.Artifact.FilesEntry
	1,  // 6: meridian.plugin.v1.CompileError.pos:type_name -> meridian.plugin.v1.Position
	5,  // 7: meridian.plugin.v1.DescribeResponse.capabilities:type_name -> meridian.plugin.v1.Capabilities
	4,  // 8: meridian.plugin.v1.EmitRequest.graph:type_name -> meridian.plugin.v1.ResourceGraph
	6,  // 9: meridian.plugin.v1.EmitResponse.artifact:type_name -> meridian.plugin.v1.Artifact
	7,  // 10: meridian.plugin.v1.EmitResponse.warnings:type_name -> meridian.plugin.v1.Warning
	8,  // 11: meridian.plugin.v1.EmitResponse.error:type_name -> meridian.plugin.v1.CompileError
	9,  // 12: meridian.plugin.v1.Emitter.Describe:input_type -> meridian.plugin.v1.DescribeRequest
	11, // 13: meridian.plugin.v1.Emitter.Emit:input_type -> meridian.plugin.v1.EmitRequest
	10, // 14: meridian.plugin.v1.Emitter.Describe:output_type -> meridian.plugin.v1.DescribeResponse
	12, // 15: meridian.plugin.v1.Emitter.Emit:output_type -> meridian.plugin.v1.EmitResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_meridian_plugin_v1_plugin_proto_init() }
func file_meridian_plugin_v1_plugin_proto_init() {
	if File_meridian_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meridian_plugin_v1_plugin_proto_rawDesc), len(file_meridian_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meridian_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_meridian_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_meridian_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_meridian_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_meridian_plugin_v1_plugin_proto = out.File
	file_meridian_plugin_v1_plugin_proto_goTypes = nil
	file_meridian_plugin_v1_plugin_proto_depIdxs = nil
}
