package puppet

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// Artifact file paths. They are constants rather than inline strings so a test
// and a runner can refer to the same names.
const (
	// ManifestPath holds the class: every resource this document declares.
	ManifestPath = "manifests/init.pp"
	// SitePath holds the node statement that assigns the class to the host.
	// Keeping the two apart is what lets the class be reused by a site that
	// classifies nodes some other way.
	SitePath = "site.pp"
)

// header marks the output as generated. Puppet manifests are commonly edited in
// place, and an operator who does not know a file is compiled will lose their
// changes on the next run without ever being told why.
const header = "# Generated by Meridian. Do not edit; this file is compiled from a Meridian document.\n"

// serialise renders a manifest into its final files. This stage performs no
// mapping and no ordering: everything it writes was decided by transform and
// sort, so the same manifest always renders to the same bytes.
//
// It owns every formatting decision, including the one Puppet authors care
// most about: the arrows in a resource body are aligned on the longest
// attribute name. Alignment is derived from the resource's own attributes
// rather than the widest in the file, which is what a Puppet style guide asks
// for and, more usefully here, what keeps an edit to one resource from
// rewriting the bytes of every other.
func serialise(m *manifest) (map[string]string, error) {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\nclass " + m.Class + " {\n")
	for i, r := range m.Resources {
		if i > 0 {
			b.WriteString("\n")
		}
		if err := writeResource(&b, r); err != nil {
			return nil, err
		}
	}
	b.WriteString("}\n")

	site := header + "\nnode '" + m.Host + "' {\n  include " + m.Class + "\n}\n"
	return map[string]string{
		ManifestPath: b.String(),
		SitePath:     site,
	}, nil
}

// writeResource lays one declaration out in a fixed attribute order: ensure
// first because it is what an operator reads to know what the resource does,
// then the remaining attributes alphabetically, then the metaparameters that
// place the resource in the graph. Order is part of the output's identity, so
// it is decided here once rather than left to map iteration.
func writeResource(b *strings.Builder, r resource) error {
	rows, err := attributeRows(r)
	if err != nil {
		return err
	}

	width := 0
	for _, row := range rows {
		if len(row.name) > width {
			width = len(row.name)
		}
	}

	fmt.Fprintf(b, "  %s { '%s':\n", r.Type, r.Title)
	for _, row := range rows {
		fmt.Fprintf(b, "    %-*s => %s,\n", width, row.name, row.value)
	}
	b.WriteString("  }\n")
	return nil
}

type row struct{ name, value string }

func attributeRows(r resource) ([]row, error) {
	var rows []row
	if ensure, ok := r.Attrs["ensure"]; ok {
		v, err := literal(ensure, r)
		if err != nil {
			return nil, err
		}
		rows = append(rows, row{"ensure", v})
	}

	names := make([]string, 0, len(r.Attrs))
	for name := range r.Attrs {
		if name != "ensure" {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		v, err := literal(r.Attrs[name], r)
		if err != nil {
			return nil, err
		}
		rows = append(rows, row{name, v})
	}

	if len(r.Require) > 0 {
		rows = append(rows, row{"require", references(r.Require)})
	}
	if len(r.Notify) > 0 {
		rows = append(rows, row{"notify", references(r.Notify)})
	}
	return rows, nil
}

// references renders one or more resource references. A single reference is
// written bare rather than as a one-element array, which is both what Puppet
// accepts and what an author would have written.
func references(refs []reference) string {
	if len(refs) == 1 {
		return refs[0].String()
	}
	parts := make([]string, 0, len(refs))
	for _, ref := range refs {
		parts = append(parts, ref.String())
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// literal renders a param value as Puppet source.
//
// A value that cannot be represented is an error rather than a best-effort
// rendering: a param the author wrote is either compiled faithfully or refused,
// and Go's default formatting of an unexpected type would produce a manifest
// that parses and means something else.
func literal(v any, r resource) (string, error) {
	switch t := v.(type) {
	case bareword:
		return string(t), nil
	case string:
		return quote(t), nil
	case bool:
		return strconv.FormatBool(t), nil
	case int:
		return strconv.Itoa(t), nil
	case int32:
		return strconv.FormatInt(int64(t), 10), nil
	case int64:
		return strconv.FormatInt(t, 10), nil
	case float64:
		// A float that is a whole number came from a document that wrote an
		// integer, and writing it back with a fractional part would change what
		// the manifest means for an attribute like a uid.
		if t == float64(int64(t)) {
			return strconv.FormatInt(int64(t), 10), nil
		}
		return strconv.FormatFloat(t, 'f', -1, 64), nil
	case []any:
		parts := make([]string, 0, len(t))
		for _, item := range t {
			s, err := literal(item, r)
			if err != nil {
				return "", err
			}
			parts = append(parts, s)
		}
		return "[" + strings.Join(parts, ", ") + "]", nil
	case map[string]any:
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			s, err := literal(t[k], r)
			if err != nil {
				return "", err
			}
			parts = append(parts, quote(k)+" => "+s)
		}
		return "{ " + strings.Join(parts, ", ") + " }", nil
	default:
		return "", &Error{
			Target: Name, Resource: r.ResourceID,
			Rule: "unrepresentable-value", Pos: r.Pos,
			Msg: fmt.Sprintf("a value of type %T cannot be written as Puppet source", v),
		}
	}
}

// quote renders a string as a Puppet string literal.
//
// Single quotes are preferred because Puppet does not interpolate inside them,
// so a value holding a dollar sign stays the value the author wrote without any
// escaping at all. A string that a single-quoted literal cannot hold falls back
// to double quotes, where interpolation has to be escaped explicitly.
func quote(s string) string {
	if !strings.ContainsAny(s, "'\\\n\r\t") {
		return "'" + s + "'"
	}
	var b strings.Builder
	b.WriteByte('"')
	for _, c := range s {
		switch c {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '$':
			b.WriteString(`\$`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}
